const PROJECT_STATUS_PENDING = '0'
const PROJECT_STATUS_INPROGRESS = '1'
const PROJECT_STATUS_REVIEW = '2'
const PROJECT_STATUS_COMPLETED = '3'
const PROJECT_STATUS_ONLEAVE = '4'
const PROJECT_STATUS_CANCELLED = '5'
const PROJECT_STATUS_DELETED = '6'

const ProjectStatusEnum = {
  [PROJECT_STATUS_PENDING]: PROJECT_STATUS_PENDING,
  [PROJECT_STATUS_INPROGRESS]: PROJECT_STATUS_INPROGRESS,
  [PROJECT_STATUS_REVIEW]: PROJECT_STATUS_REVIEW,
  [PROJECT_STATUS_COMPLETED]: PROJECT_STATUS_COMPLETED,
  [PROJECT_STATUS_ONLEAVE]: PROJECT_STATUS_ONLEAVE,
  [PROJECT_STATUS_CANCELLED]: PROJECT_STATUS_CANCELLED,
  [PROJECT_STATUS_DELETED]: PROJECT_STATUS_DELETED
}

const ProjectStatusEnumTransl = {
  [PROJECT_STATUS_PENDING]: 'constant.status.pending',
  [PROJECT_STATUS_INPROGRESS]: 'constant.status.inProgress',
  [PROJECT_STATUS_REVIEW]: 'constant.status.review',
  [PROJECT_STATUS_COMPLETED]: 'constant.status.completed',
  [PROJECT_STATUS_ONLEAVE]: 'constant.status.onLeave',
  [PROJECT_STATUS_CANCELLED]: 'constant.status.cancelled',
  [PROJECT_STATUS_DELETED]: 'constant.status.deleted'
}

const ProjectStatusEnumArr = [
  PROJECT_STATUS_PENDING,
  PROJECT_STATUS_INPROGRESS,
  PROJECT_STATUS_REVIEW,
  PROJECT_STATUS_COMPLETED,
  PROJECT_STATUS_ONLEAVE,
  PROJECT_STATUS_CANCELLED,
  PROJECT_STATUS_DELETED
]

export default ProjectStatusEnumTransl

export {
  PROJECT_STATUS_PENDING,
  PROJECT_STATUS_INPROGRESS,
  PROJECT_STATUS_REVIEW,
  PROJECT_STATUS_COMPLETED,
  PROJECT_STATUS_ONLEAVE,
  PROJECT_STATUS_CANCELLED,
  PROJECT_STATUS_DELETED
}
